version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: qurator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./q_db.sql:/docker-entrypoint-initdb.d/q_db.sql

  app:
    image: docker_python_bot:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:Qwerty@db:5432/qurator_db
    ports:
      - "5432:5432"
volumes:
  postgres_data:
